CREATE DATABASE cafe_draft;
CREATE TABLE categories(
	c_id SERIAL PRIMARY KEY,
	c_name VARCHAR(50) NOT NULL
);
CREATE TABLE ingredients(
	i_id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	i_name VARCHAR(50) NOT NULL
);
-- CREATE TABLE items();